# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0002_herramienta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='existencias',
            field=models.PositiveIntegerField(),
        ),
    ]
