# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
