# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nickname',
        ),
    ]
