# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_proyecto_usuario'),
        ('usuarios', '0003_auto_20171109_0424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
