# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('materiales', '0001_initial'),
        ('herramientas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaentrega', models.DateField()),
                ('direccion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('encargado', models.CharField(max_length=50)),
                ('totalherramientas', models.IntegerField()),
                ('totalmaterial', models.IntegerField()),
                ('Herramienta', models.ManyToManyField(blank=True, to='herramientas.herramienta')),
                ('Material', models.ManyToManyField(blank=True, to='materiales.material')),
                ('Usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
