# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_proyecto_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='totalherramientas',
        ),
    ]
