# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_remove_proyecto_totalherramientas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='totalmaterial',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
